image: python:3.7

before_script:
  - python --version 
  - pip install -r requirements.txt

stages:
  - Static Analysis
  - Test
  - Plan
  - Apply Changes

pylint:
  stage: Static Analysis
  only:
    refs:
      - merge_requests
    changes:
      - ./**/*.py
      - .gitlab-ci.yml
  script:
    - pylint *.py


pytest:
  stage: Test
  only:
    refs:
      - merge_requests
    changes:
      - ./**/*.py
      - .gitlab-ci.yml
  script:
    - python -m pytest

create_plan:
  stage: Plan
  script:
    - ./domains.py plan -s godaddy_state.json -o godaddy_plan.json
  artifacts:
    paths:
      - godaddy_plan.json
    expire_in: 1 hour
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes: 
        - godaddy_state.json
        - .gitlab-ci.yml
    - if: $CI_COMMIT_REF_NAME == 'master'

run_plan:
  stage: Apply Changes
  needs:
    - create_plan
  script:
    - ./domains.py apply -s godaddy_plan.json
  rules:
    - if: $CI_COMMIT_REF_NAME == 'master'
      changes: 
        - godaddy_state.json
      when: manual

